### ISSUE TITLE
Address product back log comments

### ISSUE THREAD

**Issue by obedappiah** [COS420-Fall24/TeamH#100]
The comments from Deliverable 2 must be addressed.

For any comment that was not addressed, deduct -2 points. 

All unaddressed comments are carried forward by default to the next deliverable as well

https://docs.google.com/spreadsheets/d/1RG28is-MV7BbFO0p168DFG8rVWGDoqalXujKYEOIt7o/edit?gid=616909607#gid=616909607

**Comment by Linkaboy** [comment]
There were no comments to address :D

**Comment by Linkaboy** [comment]
Nevermind I lied

**Comment by Linkaboy** [comment]
Nevermind I didn't lie
