### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by antAmaine** [COS420-Fall24/TeamH#130]
Setup Continuous Integration for your team’s Github repo using Github Actions or CircleCI.

Here[ relevant](https://github.com/skills/hello-github-actions)[ tutorials](https://github.com/IgnusG/jest-report-action)[ for](https://docs.github.com/en/actions/using-workflows/about-workflows) Github Actions

Here is a [repo](https://github.com/2022-autumn-cos-420/TeamC) from last year with CI correctly set up 
The free version of CircleCI should also work for your project’s size

When any commit is pushed to main, all the tests should be run and any failing tests should cause the push to be rejected

Survive Dr. Greg’s Nefarious Commit!

Dr. Greg will mangle your code and push it to your main branch

If the push is not rejected by your continuous integration tests, -10

If the push is not rejected, your team will also have to deal with getting rid of Dr. Greg’s Nefarious Commit.

Who knows when this sneaky doctor will strike again!?!?

Dr. Greg is just pushing a commit that mangles your code. There are no "github specific" malicious behaviors like changing permissions on your repository that your app's tests should detect.

[assignment](https://docs.google.com/document/d/1p2oxRSrj54ZQbdwzGynpenIIYKNB2XUhLoMQWmjpOG0/edit?usp=sharing)

**Comment by KemptonM** [comment]
Disabled the ability to commit directly to main branch.
We will now need to create new feature branches and send our commits there, then pull request to merge the feature branch into main.
Requires 1 approval of another developer.
This should block Dr. Greg's nefarious commit
