### ISSUE TITLE
SRS Feedback

### ISSUE THREAD

**Issue by antAmaine** [COS420-Fall24/TeamH#135]
If the UI mockups are not updated significantly i.e. at least 50% more and prior ones improved, deduct -10 points. This is not only the designer's task but they should lead this.
Did improve from last time
-5 not at the level of detail shown in the example deliverables
See the examples and summary at top of grading feedback

**Comment by Linkaboy** [comment]
I addressed the commend that Dr. Greg gave

**Comment by Linkaboy** [comment]
UI Markups are in a different issue, so I am leaving that for whoever is assigned to those models.
