### ISSUE TITLE
Create mockup for interactive "explain highlighted code" screen

### ISSUE THREAD

**Issue by KemptonM** [COS420-Fall24/TeamH#156]
Dr. Greg suggested we "make mocks with concrete values i.e. the code, the actual text you'd like the AI to say, etc, for your feature."
Minimum values we'll need on this screen:
"inputted code"
"highlighted lines of code"
"LLM's explanation for highlighted lines of code"

**Comment by KemptonM** [comment]
Please put a link to your work for this issue. It's set for quality checking but I can't see the mockup. @antAmaine

**Comment by antAmaine** [comment]
[Mock Up Board](https://github.com/COS420-Fall24/TeamH/issues/156#issue-2663123858)
