### ISSUE TITLE
Put tasks within the sprint backlog, documentation, requirements, UI mockup(non-technical stories)

### ISSUE THREAD

**Issue by Benji887** [COS420-Fall24/TeamH#52]
Use this template
https://docs.google.com/spreadsheets/d/18AXZZxBCle6GE3ufvEgtNAKRVHvWBjZV/edit?gid=1448491115#gid=1448491115

**Comment by obedappiah** [comment]
Use this Template
https://docs.google.com/spreadsheets/d/18AXZZxBCle6GE3ufvEgtNAKRVHvWBjZV/edit?gid=1448491115#gid=1448491115
