### ISSUE TITLE
Read quality checking  Policy

### ISSUE THREAD

**Issue by obedappiah** [COS420-Fall24/TeamH#67]
https://docs.google.com/document/d/1yX_T35Icg5LprIkoDXDYKqEtuX1bBjN7I55CxWWG16Y/edit#heading=h.1ceaaw5y5sc7

**Comment by KemptonM** [comment]
https://docs.google.com/document/d/1yX_T35Icg5LprIkoDXDYKqEtuX1bBjN7I55CxWWG16Y/edit#heading=h.1ceaaw5y5sc7
