### ISSUE TITLE
Add Description to each Task

### ISSUE THREAD

**Issue by antAmaine** [COS420-Fall24/TeamH#79]
Each task should have the grading feedback/rubric information inside the task, for that task. The task assignee should have everything they need to know to do the task well, by just looking at the task. (Also for the quality checker). <-- like this

The best option is to pull the description directly from the documentation and link any additional documentation needed in the task

**Comment by Linkaboy** [comment]
Assigned a description for each one of my task in the SRS and Software secions

**Comment by antAmaine** [comment]
you only put the grading requirements,those descriptions are not substantial enough to explain how to do the task nor do they link to relevant documents

**Comment by Linkaboy** [comment]
> you only put the grading requirements,those descriptions are not substantial enough to explain how to do the task nor do they link to relevant documents

I placed in the comments what to do. I will move them to the description. The comments provide the scope of what that particular section should look like along with the examples. The only information not provided are the specifics of the project itself which has not been determined fully. If there has been a document for those specifics I will comment it in after looking making sure all the assignments are properly formatted

**Comment by KemptonM** [comment]
closing this as it is too close to deadline to worry about housekeeping
