### ISSUE TITLE
Update tasks for use case descriptions

### ISSUE THREAD

**Issue by KemptonM** [COS420-Fall24/TeamH#89]
## [Use case description document](https://docs.google.com/document/d/1hleCBBLqHgh9Q4TtHEqo8a5ycUbH8VKK/edit)

We must develop our use case description document. Let's create an issue for each use case we will describe. Please start with the ones most essential to our app's core functions.

**Comment by KemptonM** [comment]
I'm starting with "input code snippet". Seems like the most important one.

**Comment by antAmaine** [comment]
added mine and the IDs can be changed. Can someone looks through my description field I think that mine are to vague
