### ISSUE TITLE
Add new tasks to sprint backlog

### ISSUE THREAD

**Issue by Benji887** [COS420-Fall24/TeamH#99]
### 5pts
[Sprint Backlog Sheet](https://docs.google.com/spreadsheets/d/1oDNgP2IN1xDiezXgmG1IIjvmgrrypGin_CCjcL8afsM/edit?gid=273915884#gid=273915884)
* Contains only the stories (user stories and technical and non-technical stories) you commit to working on and delivering for Deliverable 3.  Should reflect the product backlog. That is, all the user stories that are assigned to Sprint 3 in the product backlog, should be shown in the Sprint Backlog 3
  * For any missing user story, deduct -2 points.
  * If the Sprint Backlog 4 does not reflect the product backlog, deduct -5 points.
* You must have other technical tasks in your backlog otherwise -5.
* You must have other tasks in the backlog, like documentation, requirements, UI mockups, etc. As covered in class sessions, these are called non-technical stories. Otherwise -5.
* Sprint backlog must have accurate information about who did what % of the work. The sprint retrospective is a good time to fill that in, so you can see the difference between planned and actual effort.

**Comment by KemptonM** [comment]
I duplicated last week's backlog in the same document as a new sheet
